---
- name: Configure IPv6
  hosts: routers
  gather_facts: false

  tasks:
    - name: configure IPv6 on interface g1
      cisco.ios.ios_l3_interfaces:
        config:
          - name: "GigabitEthernet1"
            ipv6: 
            - address: "{{ ipv6_subnet_g1 }}"
              enable: true

    - name: configure IPV6 on interface g4
      cisco.ios.ios_l3_interfaces:
        config:
          - name: "GigabitEthernet4"
            ipv6:
              - address: "{{ ipv6_subnet_g4 }}"
                enable: true

    - name: configure routing on interface g1
      cisco.ios.ios_ospf_interfaces:
        config:
          - name: "GigabitEthernet1"
            address_family:
              - afi: ipv6
                process:
                  id: 1
                  area_id: 1

    - name: configure routing on interface g4
      cisco.ios.ios_ospf_interfaces:
        config:
          - name: "GigabitEthernet4"
            address_family:
              - afi: ipv6
                process:
                  id: 1
                  area_id: 1

    - name: save configuration
      ios_config:
        save_when: modified
